AllCops:
  Exclude:
    - "bin/**/*"
    - "node_modules/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 130

Lint/Debugger:
  Description: 'Check for debugger calls.'
  Enabled: true

Layout/BlockAlignment:
  Description: 'Align block ends correctly.'
  Enabled: true

Style/StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#consistent-string-literals'
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  Enabled: false